config/routes.rb
Rails.application.routes.draw do
  resources :production_orders
  resources :machines
  resources :inventories
  resources :orders
  resources :customers
  resources :enterprises
  root "home#index"
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :enterprise
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[ show edit update destroy ]

  # GET /inventories
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  def create
    @inventory = Inventory.new(inventory_params)

    if @inventory.save
      redirect_to @inventory, notice: "Inventory was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /inventories/1
  def update
    if @inventory.update(inventory_params)
      redirect_to @inventory, notice: "Inventory was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /inventories/1
  def destroy
    @inventory.destroy!
    redirect_to inventories_url, notice: "Inventory was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_params
      params.require(:inventory).permit(:sheet_type, :quantity, :width, :length, :depth, :color, :location, :enterprise_id)
    end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_with(model: inventory) do |form| %>
  <% if inventory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% inventory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :sheet_type, style: "display: block" %>
    <%= form.text_field :sheet_type %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :width, style: "display: block" %>
    <%= form.text_field :width %>
  </div>

  <div>
    <%= form.label :length, style: "display: block" %>
    <%= form.text_field :length %>
  </div>

  <div>
    <%= form.label :depth, style: "display: block" %>
    <%= form.text_field :depth %>
  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.text_field :color %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :enterprise_id, style: "display: block" %>
    <%= form.text_field :enterprise_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inventories/_inventory.html.erb
<div id="<%= dom_id inventory %>">
  <p>
    <strong>Sheet type:</strong>
    <%= inventory.sheet_type %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= inventory.quantity %>
  </p>

  <p>
    <strong>Width:</strong>
    <%= inventory.width %>
  </p>

  <p>
    <strong>Length:</strong>
    <%= inventory.length %>
  </p>

  <p>
    <strong>Depth:</strong>
    <%= inventory.depth %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= inventory.color %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= inventory.location %>
  </p>

  <p>
    <strong>Enterprise:</strong>
    <%= inventory.enterprise_id %>
  </p>

</div>

app/views/inventories/edit.html.erb
<% content_for :title, "Editing inventory" %>

<h1>Editing inventory</h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= link_to "Show this inventory", @inventory %> |
  <%= link_to "Back to inventories", inventories_path %>
</div>

app/views/inventories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Inventories" %>

<h1>Inventories</h1>

<div id="inventories">
  <% @inventories.each do |inventory| %>
    <%= render inventory %>
    <p>
      <%= link_to "Show this inventory", inventory %>
    </p>
  <% end %>
</div>

<%= link_to "New inventory", new_inventory_path %>

app/views/inventories/new.html.erb
<% content_for :title, "New inventory" %>

<h1>New inventory</h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= link_to "Back to inventories", inventories_path %>
</div>

app/views/inventories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inventory %>

<div>
  <%= link_to "Edit this inventory", edit_inventory_path(@inventory) %> |
  <%= link_to "Back to inventories", inventories_path %>

  <%= button_to "Destroy this inventory", @inventory, method: :delete %>
</div>