config/routes.rb
Rails.application.routes.draw do
  resources :production_orders
  resources :machines
  resources :inventories
  resources :orders
  resources :customers
  resources :enterprises
  root "home#index"
end

app/controllers/enterprises_controller.rb
class EnterprisesController < ApplicationController
  before_action :set_enterprise, only: %i[ show edit update destroy ]

  # GET /enterprises
  def index
    @enterprises = Enterprise.all
  end

  # GET /enterprises/1
  def show
  end

  # GET /enterprises/new
  def new
    @enterprise = Enterprise.new
  end

  # GET /enterprises/1/edit
  def edit
  end

  # POST /enterprises
  def create
    @enterprise = Enterprise.new(enterprise_params)

    if @enterprise.save
      redirect_to @enterprise, notice: "Enterprise was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /enterprises/1
  def update
    if @enterprise.update(enterprise_params)
      redirect_to @enterprise, notice: "Enterprise was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /enterprises/1
  def destroy
    @enterprise.destroy!
    redirect_to enterprises_url, notice: "Enterprise was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enterprise
      @enterprise = Enterprise.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enterprise_params
      params.require(:enterprise).permit(:name, :email, :phone, :address)
    end
end

app/helpers/enterprises_helper.rb
module EnterprisesHelper
end

app/views/enterprises/_enterprise.html.erb
<div id="<%= dom_id enterprise %>">
  <p>
    <strong>Name:</strong>
    <%= enterprise.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= enterprise.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= enterprise.phone %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= enterprise.address %>
  </p>

</div>

app/views/enterprises/_form.html.erb
<%= form_with(model: enterprise) do |form| %>
  <% if enterprise.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(enterprise.errors.count, "error") %> prohibited this enterprise from being saved:</h2>

      <ul>
        <% enterprise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/enterprises/edit.html.erb
<% content_for :title, "Editing enterprise" %>

<h1>Editing enterprise</h1>

<%= render "form", enterprise: @enterprise %>

<br>

<div>
  <%= link_to "Show this enterprise", @enterprise %> |
  <%= link_to "Back to enterprises", enterprises_path %>
</div>

app/views/enterprises/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Enterprises" %>

<h1>Enterprises</h1>

<div id="enterprises">
  <% @enterprises.each do |enterprise| %>
    <%= render enterprise %>
    <p>
      <%= link_to "Show this enterprise", enterprise %>
    </p>
  <% end %>
</div>

<%= link_to "New enterprise", new_enterprise_path %>

app/views/enterprises/new.html.erb
<% content_for :title, "New enterprise" %>

<h1>New enterprise</h1>

<%= render "form", enterprise: @enterprise %>

<br>

<div>
  <%= link_to "Back to enterprises", enterprises_path %>
</div>

app/views/enterprises/show.html.erb
<% content_for :navigation do %>
  <li class="nav-item">
    <%= link_to 'Clientes', customers_path,  class: "btn btn-outline-light ml-4" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Pedidos', orders_path,  class: "btn btn-outline-light ml-4" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Estoque', inventories_path,  class: "btn btn-outline-light ml-4" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Maquinas', machines_path,  class: "btn btn-outline-light ml-4" %>
  </li>
    <li class="nav-item">
    <%= link_to 'Ordem de Produção', production_orders_path,  class: "btn btn-outline-light ml-4" %>
  </li>
<% end %>

<p style="color: green"><%= notice %></p>

<%= render @enterprise %>

<div>
  <%= link_to "Edit this enterprise", edit_enterprise_path(@enterprise) %> |
  <%= link_to "Back to enterprises", enterprises_path %>

  <%= button_to "Destroy this enterprise", @enterprise, method: :delete %>
</div>