config/routes.rb
Rails.application.routes.draw do
  resources :production_orders
  resources :machines
  resources :inventories
  resources :orders
  resources :customers
  resources :enterprises
  root "home#index"
end

app/models/machine.rb
class Machine < ApplicationRecord
  belongs_to :enterprise

  enum status: { 'available' => 0, 'under_maintenance' => 5 }
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: %i[ show edit update destroy ]

  # GET /machines
  def index
    @machines = Machine.all
  end

  # GET /machines/1
  def show
  end

  # GET /machines/new
  def new
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit
  end

  # POST /machines
  def create
    @machine = Machine.new(machine_params)

    if @machine.save
      redirect_to @machine, notice: "Machine was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /machines/1
  def update
    if @machine.update(machine_params)
      redirect_to @machine, notice: "Machine was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /machines/1
  def destroy
    @machine.destroy!
    redirect_to machines_url, notice: "Machine was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def machine_params
      params.require(:machine).permit(:name, :machine_type, :status, :enterprise_id)
    end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_form.html.erb
<%= form_with(model: machine) do |form| %>
  <% if machine.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
        <% machine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :machine_type, style: "display: block" %>
    <%= form.text_field :machine_type %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :enterprise_id, style: "display: block" %>
    <%= form.text_field :enterprise_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/machines/_machine.html.erb
<div id="<%= dom_id machine %>">
  <p>
    <strong>Name:</strong>
    <%= machine.name %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= machine.machine_type %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= machine.status %>
  </p>

  <p>
    <strong>Enterprise:</strong>
    <%= machine.enterprise_id %>
  </p>

</div>

app/views/machines/edit.html.erb
<% content_for :title, "Editing machine" %>

<h1>Editing machine</h1>

<%= render "form", machine: @machine %>

<br>

<div>
  <%= link_to "Show this machine", @machine %> |
  <%= link_to "Back to machines", machines_path %>
</div>

app/views/machines/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Machines" %>

<h1>Machines</h1>

<div id="machines">
  <% @machines.each do |machine| %>
    <%= render machine %>
    <p>
      <%= link_to "Show this machine", machine %>
    </p>
  <% end %>
</div>

<%= link_to "New machine", new_machine_path %>

app/views/machines/new.html.erb
<% content_for :title, "New machine" %>

<h1>New machine</h1>

<%= render "form", machine: @machine %>

<br>

<div>
  <%= link_to "Back to machines", machines_path %>
</div>

app/views/machines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @machine %>

<div>
  <%= link_to "Edit this machine", edit_machine_path(@machine) %> |
  <%= link_to "Back to machines", machines_path %>

  <%= button_to "Destroy this machine", @machine, method: :delete %>
</div>